language: node_js
node_js:
  - "8"
  - "10"
  - node
# safelist
branches:
  only:
  - master

before_install:
  # yarn
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.13.0
  - export PATH="$HOME/.yarn/bin:$PATH"

script:
  - yarn
  - yarn lint
  - yarn test:all
  - yarn build:lib
  - yarn build:lib:schematics

after_success: yarn report-coverage

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

dist: trusty
cache:
  yarn: true
  directories:
    - node_modules
